name: ERC-5164 Fork Tests

on: ["push", "pull_request"]

env:
  FOUNDRY_PROFILE: ci

jobs:
  forge:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1.0.0

      - name: Run Forge coverage
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
        run: |
          forge coverage --report lcov && lcov --remove lcov.info -o lcov.info 'test/contracts/mock/*' 'test/fork' 'test/unit' 'script/*'
        id: coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1.5.0
        with:
          coverage-files: lcov.info
          minimum-coverage: 90
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yarn dependencies and generate types
        run: |
          yarn
          yarn typechain

      - name: Run relayCalls Arbitrum fork tests
        continue-on-error: true
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
          FORK_ENABLED: true
          HDWALLET_MNEMONIC: ${{ secrets.HDWALLET_MNEMONIC }}
        run: |
          yarn fork:startRelayCallsArbitrumMainnet

      - name: Run executeCalls Arbitrum fork tests
        continue-on-error: true
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
          FORK_ENABLED: true
          HDWALLET_MNEMONIC: ${{ secrets.HDWALLET_MNEMONIC }}
        run: |
          yarn fork:startExecuteCallsArbitrumMainnet
